[package]
name = "dev-ports-tray"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
crossbeam-channel = "0.5"
nix = { version = "0.29", features = ["signal"] }
thiserror = "1"
winit = "0.29"
tray-icon = "0.13"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1

